#  This config is limited to this project only otherwise for projects with client and server on different repo config will be much easier
# ! this config didn't worked as i couldn't run puppeteer on circle ci

version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
        - image: cimg/node:18.12.1-browsers
        - image: cimg/redis:7.0
        - image: mongo:latest
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:    # you don't need to this normally it's done automatically by circleci
          name: Start Client
          command: npm run react
          background: true
      - run:
          name: Start Server  # # you don't need to this normally it's done automatically by circleci
          command: npm start
          background: true
      - run:
          name: Run tests
          command: npm run test
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./client/build
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master